### ISSUE TITLE
Game crashed on card preview

### ISSUE THREAD

**Issue by ghost** [Alchyr/sts-ram-saver#1]
00:11:48.562 ERROR core.CardCrawlGame> Exception caught
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: yorigamiResources/images/cards/SwindleCard_p.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.RealTexture.<init>(RealTexture.java:23) ~[ramsaver.jar:?]
	at optispire.RamSaver$FileTextureSupplier.get(RamSaver.java:182) ~[ramsaver.jar:?]
	at optispire.RamSaver$FileTextureSupplier.get(RamSaver.java:164) ~[ramsaver.jar:?]
	at optispire.RamSaver.loadTexture(RamSaver.java:250) ~[ramsaver.jar:?]
	at optispire.RamSaver.getTexture(RamSaver.java:338) ~[ramsaver.jar:?]
	at optispire.RamSaver.getTexture(RamSaver.java:327) ~[ramsaver.jar:?]
	at com.badlogic.gdx.graphics.Texture.getRealTexture(Texture.java:113) ~[?:?]
	at optispire.patches.HandleRenderingFakes$FakeTextures.handleFakeTexture(HandleRenderingFakes.java:209) ~[ramsaver.jar:?]
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.draw(SpriteBatch.java) ~[?:?]
	at com.megacrit.cardcrawl.screens.SingleCardViewPopup.renderPortrait(SingleCardViewPopup.java:555) ~[?:?]
	at com.megacrit.cardcrawl.screens.SingleCardViewPopup.render(SingleCardViewPopup.java:349) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:455) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]
Caused by: java.io.IOException: Error loading pixmap: decoder init failed for stream
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:90) ~[desktop-1.0.jar:?]
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146) ~[desktop-1.0.jar:?]
	... 15 more
Controllers: removed manager for application, 0 managers active
Game crashed.
Version Info:
 - Java version (1.8.0_144)
 - Slay the Spire (12-18-2022)
 - ModTheSpire (3.30.3)
Mod list:
 - basemod (5.52.3)
 - stslib (2.10.1)
 - TheJungle (1.5.2)
 - actlikeit (1.2.7)
 - bundlecore (4.0.4)
 - aspiration (1.9.5)
 - beakedthecultist-sts (0.7.3)
 - betterAltar (1.4)
 - betterLab (1.0)
 - betterNote (1.3)
 - betterStone (1.1)
 - betterSkull (1.2)
 - betterThird (1.5)
 - BootUpWindows (0.0.0)
 - CaffeInSpire (1.0.0)
 - extendedui (4.3.7)
 - ferrothorn (1.0)
 - Gensokyo (4.0.0)
 - GooglyMod (1.9.0)
 - GungeonMod (2.0.6)
 - Hermit (1.54)
 - hubris (0.25.1)
 - klkmod (1.2)
 - MysteryDungeon (2.0.6)
 - ReimuMod (1.1)
 - conspire (1.7.0)
 - RiskOfRelics (2.2.0)
 - RunHistoryPlus (1.8.1)
 - TestersMod (1.8.1)
 - DrifterMod (1.1)
 - BlackRuseMod (0.9.4)
 - theVacant (1.0.1)
 - WildCard (1.0.0)
 - sovietmod (1.2.9)
 - Koishi (2.1.0)
 - ruina (3.7.0)
 - AKDsMoreRelics (1.5.0)
 - LazyManKits (1.4.10)
 - theflagbearer (1.5.1)
 - intentgraph (0.2.1)
 - hollowmod (1.8.3)
 - RandomCharacterButton (1.1.0)
 - RandomCharacterMod (1.0.1)
 - RhythmGirl (0.1.11)
 - Yorigami (1.1.1)
 - bundle_of_food (2.1.6)
 - anniv5 (2.1.3)
 - expansionPacks (1.0.3)
 - IceBreaker (1.2.1)
 - Undermine (1.0.3)
 - OptimizeTheSpire (1.1.0)
 - versiontwocompatible (2.2.6)
 - AIAdditions (1.5.0)
 - Abyss (1.3.0)
 - ojb_Bestiary (0.1.1)
 - bundle_of_content (1.5.8)
 - Bundle_Of_Peglin (2.7.3)
 - bundle_of_potions (2.3.5)
 - coloredpowertips (2.3.0)
 - CorruptTheSpire (1.4.1)
 - downfall (5.0.7)
 - Elementarium (1.10.0)
 - Halation (0.0.18)
 - Hallownest (1.0.2)
 - MGRMod (1.0.3)
 - MarisaContinued (4.0.1)
 - Menagerie (1.6.1)
 - MoreNeow (1.0.1)
 - quickrestart (2.0.5)
 - ramsaver (0.2.1)
 - RelicStats (1.2.2)
 - Team TouhouSpire Remilia Scarlet Mode 3.3.8 (3.3.5)
 - constructmod (1.1.0)
 - YukariMod (0.9.15)
 - KombatMod (0.7.6)
 - PatchouliMod (1.1.4)
 - thelost (1.0.7)
 - WarShipGirlsRmod (1.1)
 - WeightedPaths (1.2.5)
 - backflip (0.0.1)
 - chaofanmod (1.0.18)
 - darknessisdarknessmod (4.2.0.6.9)
 - JungleCompatibility (0.0.1)
 - LorekeeperMod (1.0.0)
 - paparatto (0.1.2)
 - bad_defect (0.3.5)
 - bad_ironclad (0.1.6)
 - bad_silent (0.1.12)
 - bad_spire (0.2.4)
 - bad_watcher (0.2.6)
 - coloredinkbottle (1.0)
 - DownfallExtension (2.7.3)
 - downfallRelicStats (1.2.2)
 - IroncladRager (2.0.0)
 - omori (4.0)
 - permNeow (1)
 - Scapegoat (1.5.0)
 - spirelocations (1.1.1)
 - TerrariaRelics (0.1.1)
 - Traveler (1.2.3)
 - Sts-AdministrixMod (0.9.3.2)
 - eatyourbeetsvg-theanimator (3.5.9)
 - TheSenshi (1.3.0)
 - thevixen (1.2.7)
 - GuardsmenMod (0.4.3)
 - RainbowMod (0.4.0)
 - oceanrodent (1.3.11)
 - oceanmod (1.0.18)
 - coloredmap (2.4.1)
 - downfallcharbossapi (1.1.0)
 - HighlightPath (0.0.3)
 - bladegunner (1.5.2)
 - bladegunner-downfall (1.2.3)
 - ShapesMod (1.0.2)

Mods in stacktrace:
 - ramsaver (0.2.1)
Cause:
com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: yorigamiResources/images/cards/SwindleCard_p.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:148)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.RealTexture.<init>(RealTexture.java:23)
	at optispire.RamSaver$FileTextureSupplier.get(RamSaver.java:182)
	at optispire.RamSaver$FileTextureSupplier.get(RamSaver.java:164)
	at optispire.RamSaver.loadTexture(RamSaver.java:250)
	at optispire.RamSaver.getTexture(RamSaver.java:338)
	at optispire.RamSaver.getTexture(RamSaver.java:327)
	at com.badlogic.gdx.graphics.Texture.getRealTexture(Texture.java:113)
	at optispire.patches.HandleRenderingFakes$FakeTextures.handleFakeTexture(HandleRenderingFakes.java:209)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.draw(SpriteBatch.java)
	at com.megacrit.cardcrawl.screens.SingleCardViewPopup.renderPortrait(SingleCardViewPopup.java:555)
	at com.megacrit.cardcrawl.screens.SingleCardViewPopup.render(SingleCardViewPopup.java:349)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:455)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: java.io.IOException: Error loading pixmap: decoder init failed for stream
	at com.badlogic.gdx.graphics.g2d.Gdx2DPixmap.<init>(Gdx2DPixmap.java:90)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:146)
	... 15 more

Full log: [mts_process_launch.log](https://github.com/Alchyr/sts-ram-saver/files/12602657/mts_process_launch.log)

**Comment by Alchyr** [comment]
This is an error that occurred within the game engine itself when attempting to load the texture. If you get this error consistently, and only with this specific card or cards from this mod, I would suggest unsubscribing and resubscribing to it to redownload it, as the files for it may have downloaded incorrectly.
